# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/client/utils.ipynb.

# %% auto 0
__all__ = ['upsert_folder', 'download_zip', 'change_suffix', 'convert_string_to_datetime', 'convert_str_to_snake_case']

# %% ../../nbs/client/utils.ipynb 2
import os
import pathlib

import zipfile
import io
import datetime as dt
import dateutil

import re

# %% ../../nbs/client/utils.ipynb 4
def upsert_folder(folder_path: str, debug_prn: bool = False):
    folder_path = os.path.dirname(folder_path)

    if debug_prn:
        print(
            {
                "upsert_folder": os.path.abspath(folder_path),
                "is_exist": os.path.exists(folder_path),
            }
        )

    if not os.path.exists(folder_path):
        os.makedirs(folder_path)

    return True

# %% ../../nbs/client/utils.ipynb 5
def download_zip(
        output_folder,
        zip_bytes_content: bytes = None,
                 zip_file_path : str = None,
                  ):
    """save bytes content to a zip file then convert html to markdown"""
    zip = None
    if zip_bytes_content:
        zip = zipfile.ZipFile(io.BytesIO(zip_bytes_content), "r")
    
    if zip_file_path:
        zip = zipfile.ZipFile(zip_file_path)
    
    if not zip:
        raise Exception("unabler to generate zip file pass zip_bytes_content or zip_file_path")
    
    zip.extractall(output_folder)

    file_ls = os.listdir(output_folder)
    return file_ls

# %% ../../nbs/client/utils.ipynb 6
def change_suffix(filename, new_extension):
    is_exist = os.path.exists(filename)

    p = pathlib.PurePath(filename)
    p = p.with_suffix(new_extension)

    if is_exist:
        p = pathlib.Path(filename)
        p = p.rename(p.with_suffix(new_extension))

    return str(p)

# %% ../../nbs/client/utils.ipynb 8
def convert_string_to_datetime(datestr: str) -> dt.datetime:
    if not datestr:
        return None
    return dateutil.parser.parse(datestr)

# %% ../../nbs/client/utils.ipynb 9
def convert_str_to_snake_case(text_str, is_only_alphanumeric: bool = False):
    """converts 'snake_case_str' to 'snakeCaseStr'"""

    text_str = text_str.replace(" ", "_").lower()

    if is_only_alphanumeric:
        text_str = re.sub(r"\W+", "", text_str)

    return text_str
